"""
graph/audit_log.py
------------------
Audit logging system for knowledge graph modifications.

This module implements comprehensive audit logging for all graph modifications
(node/edge creation, updates, deletions) with timestamps and user IDs for
reproducibility and traceability.

Requirements: 18.5, 19.1, 19.2, 19.3, 19.4, 19.5
"""

import json
import sqlite3
from typing import Dict, List, Optional, Any
from datetime import datetime, timezone
from pathlib import Path
from pydantic import BaseModel, Field
from threading import Lock
import logging

logger = logging.getLogger(__name__)


class AuditLogEntry(BaseModel):
    """
    Single audit log entry for a graph modification.
    
    Requirement 19.5: System SHALL maintain an audit log of all graph
    modifications with timestamp and user ID.
    """
    
    log_id: Optional[int] = None  # Auto-generated by database
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    user_id: str = Field(default="system", description="User ID who made the modification")
    
    # Operation details
    operation_type: str = Field(..., description="create_node | update_node | delete_node | create_edge | update_edge | delete_edge")
    entity_type: str = Field(..., description="Node type or relationship type")
    entity_id: str = Field(..., description="Unique identifier of the entity")
    
    # Modification details
    modification_details: Dict[str, Any] = Field(default_factory=dict, description="Details of what was modified")
    
    # Extraction metadata (for relationships)
    extraction_method: Optional[str] = Field(None, description="Extraction method used (if applicable)")
    extractor_version: Optional[str] = Field(None, description="Version of extraction method")
    source_code_hash: Optional[str] = Field(None, description="Hash of extraction method source code")
    llm_prompt_hash: Optional[str] = Field(None, description="Hash of LLM prompt if applicable")
    
    # Provenance
    paper_id: Optional[str] = Field(None, description="Paper ID if this is a relationship extraction")
    section: Optional[str] = Field(None, description="Section of paper if applicable")
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class AuditLog:
    """
    Audit logging system for knowledge graph modifications.
    
    This system tracks all graph modifications (node/edge creation, updates,
    deletions) with timestamps and user IDs. It uses SQLite for persistent
    storage and provides query interfaces for auditing and rollback.
    
    Requirements:
    - 18.5: Log all data access for audit trail
    - 19.1: Store extraction method source code hash for reproducibility
    - 19.2: Store LLM prompt hash for all LLM-based extractions
    - 19.3: Support querying relationships by extraction method version
    - 19.4: Support rollback of extractions by method version
    - 19.5: Maintain audit log with timestamp and user ID
    """
    
    def __init__(self, db_path: Optional[str] = None):
        """
        Initialize the audit log system.
        
        Args:
            db_path: Path to SQLite database file (default: data/audit_log.db)
        
        Requirement 19.5: Maintain audit log of all graph modifications
        """
        if db_path is None:
            db_path = str(Path(__file__).parent.parent / "data" / "audit_log.db")
        
        self.db_path = db_path
        self._lock = Lock()
        self._initialize_database()
        logger.info(f"Initialized AuditLog with database at {db_path}")
    
    def _initialize_database(self):
        """
        Create audit log table if it doesn't exist.
        
        Requirement 19.5: Create audit log table for all graph modifications
        with timestamp and user ID.
        """
        # Ensure parent directory exists
        Path(self.db_path).parent.mkdir(parents=True, exist_ok=True)
        
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            
            # Create audit log table
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS audit_log (
                    log_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    timestamp TEXT NOT NULL,
                    user_id TEXT NOT NULL,
                    operation_type TEXT NOT NULL,
                    entity_type TEXT NOT NULL,
                    entity_id TEXT NOT NULL,
                    modification_details TEXT,
                    extraction_method TEXT,
                    extractor_version TEXT,
                    source_code_hash TEXT,
                    llm_prompt_hash TEXT,
                    paper_id TEXT,
                    section TEXT
                )
            """)
            
            # Create indexes for efficient querying
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS idx_timestamp 
                ON audit_log(timestamp)
            """)
            
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS idx_extraction_method 
                ON audit_log(extraction_method, extractor_version)
            """)
            
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS idx_entity 
                ON audit_log(entity_type, entity_id)
            """)
            
            cursor.execute("""
                CREATE INDEX IF NOT EXISTS idx_user 
                ON audit_log(user_id)
            """)
            
            conn.commit()
            logger.info("Audit log database initialized")
    
    def log_modification(
        self,
        operation_type: str,
        entity_type: str,
        entity_id: str,
        user_id: str = "system",
        modification_details: Optional[Dict[str, Any]] = None,
        extraction_method: Optional[str] = None,
        extractor_version: Optional[str] = None,
        source_code_hash: Optional[str] = None,
        llm_prompt_hash: Optional[str] = None,
        paper_id: Optional[str] = None,
        section: Optional[str] = None,
    ) -> int:
        """
        Log a graph modification to the audit log.
        
        Args:
            operation_type: Type of operation (create_node, update_node, delete_node, 
                           create_edge, update_edge, delete_edge)
            entity_type: Node type or relationship type
            entity_id: Unique identifier of the entity
            user_id: User ID who made the modification (default: "system")
            modification_details: Details of what was modified
            extraction_method: Extraction method used (if applicable)
            extractor_version: Version of extraction method
            source_code_hash: Hash of extraction method source code
            llm_prompt_hash: Hash of LLM prompt if applicable
            paper_id: Paper ID if this is a relationship extraction
            section: Section of paper if applicable
        
        Returns:
            log_id: Auto-generated log entry ID
        
        Requirements:
        - 19.1: Store extraction method source code hash
        - 19.2: Store LLM prompt hash for LLM-based extractions
        - 19.5: Log with timestamp and user ID
        """
        entry = AuditLogEntry(
            user_id=user_id,
            operation_type=operation_type,
            entity_type=entity_type,
            entity_id=entity_id,
            modification_details=modification_details or {},
            extraction_method=extraction_method,
            extractor_version=extractor_version,
            source_code_hash=source_code_hash,
            llm_prompt_hash=llm_prompt_hash,
            paper_id=paper_id,
            section=section,
        )
        
        with self._lock:
            with sqlite3.connect(self.db_path) as conn:
                cursor = conn.cursor()
                
                cursor.execute("""
                    INSERT INTO audit_log (
                        timestamp, user_id, operation_type, entity_type, entity_id,
                        modification_details, extraction_method, extractor_version,
                        source_code_hash, llm_prompt_hash, paper_id, section
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """, (
                    entry.timestamp.isoformat(),
                    entry.user_id,
                    entry.operation_type,
                    entry.entity_type,
                    entry.entity_id,
                    json.dumps(entry.modification_details),
                    entry.extraction_method,
                    entry.extractor_version,
                    entry.source_code_hash,
                    entry.llm_prompt_hash,
                    entry.paper_id,
                    entry.section,
                ))
                
                log_id = cursor.lastrowid
                conn.commit()
        
        logger.debug(
            f"Logged {operation_type} for {entity_type}:{entity_id} "
            f"by {user_id} (log_id={log_id})"
        )
        
        return log_id
    
    def log_node_creation(
        self,
        node_type: str,
        node_id: str,
        properties: Dict[str, Any],
        user_id: str = "system",
    ) -> int:
        """
        Log creation of a graph node.
        
        Args:
            node_type: Type of node (Paper, Taxon, Disease, Method, ScientificClaim)
            node_id: Unique node identifier
            properties: Node properties
            user_id: User ID who created the node
        
        Returns:
            log_id: Auto-generated log entry ID
        
        Requirement 19.5: Log all graph modifications
        """
        return self.log_modification(
            operation_type="create_node",
            entity_type=node_type,
            entity_id=node_id,
            user_id=user_id,
            modification_details={"properties": properties},
        )
    
    def log_edge_creation(
        self,
        relationship_type: str,
        source_id: str,
        target_id: str,
        properties: Dict[str, Any],
        user_id: str = "system",
        extraction_method: Optional[str] = None,
        extractor_version: Optional[str] = None,
        source_code_hash: Optional[str] = None,
        llm_prompt_hash: Optional[str] = None,
        paper_id: Optional[str] = None,
        section: Optional[str] = None,
    ) -> int:
        """
        Log creation of a graph relationship.
        
        Args:
            relationship_type: Type of relationship (REPORTS_ASSOCIATION, etc.)
            source_id: Source node ID
            target_id: Target node ID
            properties: Relationship properties
            user_id: User ID who created the relationship
            extraction_method: Extraction method used
            extractor_version: Version of extraction method
            source_code_hash: Hash of extraction method source code
            llm_prompt_hash: Hash of LLM prompt if applicable
            paper_id: Paper ID if this is a relationship extraction
            section: Section of paper if applicable
        
        Returns:
            log_id: Auto-generated log entry ID
        
        Requirements:
        - 19.1: Store extraction method source code hash
        - 19.2: Store LLM prompt hash for LLM-based extractions
        - 19.5: Log all graph modifications
        """
        entity_id = f"{source_id}->{target_id}"
        
        return self.log_modification(
            operation_type="create_edge",
            entity_type=relationship_type,
            entity_id=entity_id,
            user_id=user_id,
            modification_details={
                "source_id": source_id,
                "target_id": target_id,
                "properties": properties,
            },
            extraction_method=extraction_method,
            extractor_version=extractor_version,
            source_code_hash=source_code_hash,
            llm_prompt_hash=llm_prompt_hash,
            paper_id=paper_id,
            section=section,
        )
    
    def query_by_extraction_method(
        self,
        extraction_method: str,
        extractor_version: Optional[str] = None,
    ) -> List[AuditLogEntry]:
        """
        Query all relationships extracted by a specific method version.
        
        This enables auditing and rollback of extractions by method version.
        
        Args:
            extraction_method: Extraction method identifier
            extractor_version: Version of extraction method (optional)
        
        Returns:
            List of AuditLogEntry objects matching the criteria
        
        Requirement 19.3: Support querying relationships by extraction method version
        """
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            
            if extractor_version:
                cursor.execute("""
                    SELECT * FROM audit_log
                    WHERE extraction_method = ? AND extractor_version = ?
                    ORDER BY timestamp DESC
                """, (extraction_method, extractor_version))
            else:
                cursor.execute("""
                    SELECT * FROM audit_log
                    WHERE extraction_method = ?
                    ORDER BY timestamp DESC
                """, (extraction_method,))
            
            rows = cursor.fetchall()
        
        # Convert rows to AuditLogEntry objects
        entries = []
        for row in rows:
            entry = AuditLogEntry(
                log_id=row[0],
                timestamp=datetime.fromisoformat(row[1]),
                user_id=row[2],
                operation_type=row[3],
                entity_type=row[4],
                entity_id=row[5],
                modification_details=json.loads(row[6]) if row[6] else {},
                extraction_method=row[7],
                extractor_version=row[8],
                source_code_hash=row[9],
                llm_prompt_hash=row[10],
                paper_id=row[11],
                section=row[12],
            )
            entries.append(entry)
        
        logger.info(
            f"Found {len(entries)} audit log entries for "
            f"extraction_method={extraction_method}, version={extractor_version}"
        )
        
        return entries
    
    def get_relationships_by_method_version(
        self,
        extraction_method: str,
        extractor_version: Optional[str] = None,
    ) -> List[Dict[str, Any]]:
        """
        Get all relationships extracted by a specific method version.
        
        This returns the relationship details (source, target, properties)
        for all relationships extracted by the specified method version.
        
        Args:
            extraction_method: Extraction method identifier
            extractor_version: Version of extraction method (optional)
        
        Returns:
            List of relationship dictionaries with source_id, target_id, properties
        
        Requirement 19.3: Support querying relationships by extraction method version
        """
        entries = self.query_by_extraction_method(extraction_method, extractor_version)
        
        # Filter to only edge creation operations
        relationships = []
        for entry in entries:
            if entry.operation_type == "create_edge":
                relationships.append({
                    "relationship_type": entry.entity_type,
                    "source_id": entry.modification_details.get("source_id"),
                    "target_id": entry.modification_details.get("target_id"),
                    "properties": entry.modification_details.get("properties", {}),
                    "paper_id": entry.paper_id,
                    "section": entry.section,
                    "timestamp": entry.timestamp,
                })
        
        logger.info(
            f"Found {len(relationships)} relationships for "
            f"extraction_method={extraction_method}, version={extractor_version}"
        )
        
        return relationships
    
    def query_by_user(
        self,
        user_id: str,
        start_time: Optional[datetime] = None,
        end_time: Optional[datetime] = None,
    ) -> List[AuditLogEntry]:
        """
        Query all modifications by a specific user.
        
        Args:
            user_id: User ID to query
            start_time: Start of time range (optional)
            end_time: End of time range (optional)
        
        Returns:
            List of AuditLogEntry objects
        
        Requirement 19.5: Audit log with user ID
        """
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            
            query = "SELECT * FROM audit_log WHERE user_id = ?"
            params = [user_id]
            
            if start_time:
                query += " AND timestamp >= ?"
                params.append(start_time.isoformat())
            
            if end_time:
                query += " AND timestamp <= ?"
                params.append(end_time.isoformat())
            
            query += " ORDER BY timestamp DESC"
            
            cursor.execute(query, params)
            rows = cursor.fetchall()
        
        # Convert rows to AuditLogEntry objects
        entries = []
        for row in rows:
            entry = AuditLogEntry(
                log_id=row[0],
                timestamp=datetime.fromisoformat(row[1]),
                user_id=row[2],
                operation_type=row[3],
                entity_type=row[4],
                entity_id=row[5],
                modification_details=json.loads(row[6]) if row[6] else {},
                extraction_method=row[7],
                extractor_version=row[8],
                source_code_hash=row[9],
                llm_prompt_hash=row[10],
                paper_id=row[11],
                section=row[12],
            )
            entries.append(entry)
        
        return entries
    
    def query_by_time_range(
        self,
        start_time: datetime,
        end_time: datetime,
    ) -> List[AuditLogEntry]:
        """
        Query all modifications within a time range.
        
        Args:
            start_time: Start of time range
            end_time: End of time range
        
        Returns:
            List of AuditLogEntry objects
        
        Requirement 19.5: Audit log with timestamp
        """
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            
            cursor.execute("""
                SELECT * FROM audit_log
                WHERE timestamp >= ? AND timestamp <= ?
                ORDER BY timestamp DESC
            """, (start_time.isoformat(), end_time.isoformat()))
            
            rows = cursor.fetchall()
        
        # Convert rows to AuditLogEntry objects
        entries = []
        for row in rows:
            entry = AuditLogEntry(
                log_id=row[0],
                timestamp=datetime.fromisoformat(row[1]),
                user_id=row[2],
                operation_type=row[3],
                entity_type=row[4],
                entity_id=row[5],
                modification_details=json.loads(row[6]) if row[6] else {},
                extraction_method=row[7],
                extractor_version=row[8],
                source_code_hash=row[9],
                llm_prompt_hash=row[10],
                paper_id=row[11],
                section=row[12],
            )
            entries.append(entry)
        
        return entries
    
    def get_statistics(self) -> Dict[str, Any]:
        """
        Get statistics about the audit log.
        
        Returns:
            Dictionary with statistics (total entries, operations by type, etc.)
        """
        with sqlite3.connect(self.db_path) as conn:
            cursor = conn.cursor()
            
            # Total entries
            cursor.execute("SELECT COUNT(*) FROM audit_log")
            total_entries = cursor.fetchone()[0]
            
            # Operations by type
            cursor.execute("""
                SELECT operation_type, COUNT(*) 
                FROM audit_log 
                GROUP BY operation_type
            """)
            operations_by_type = dict(cursor.fetchall())
            
            # Extractions by method
            cursor.execute("""
                SELECT extraction_method, COUNT(*) 
                FROM audit_log 
                WHERE extraction_method IS NOT NULL
                GROUP BY extraction_method
            """)
            extractions_by_method = dict(cursor.fetchall())
            
            # Users
            cursor.execute("""
                SELECT user_id, COUNT(*) 
                FROM audit_log 
                GROUP BY user_id
            """)
            modifications_by_user = dict(cursor.fetchall())
        
        return {
            "total_entries": total_entries,
            "operations_by_type": operations_by_type,
            "extractions_by_method": extractions_by_method,
            "modifications_by_user": modifications_by_user,
        }


# Global audit log instance
_global_audit_log: Optional[AuditLog] = None


def get_audit_log(db_path: Optional[str] = None) -> AuditLog:
    """
    Get the global audit log instance.
    
    Args:
        db_path: Path to SQLite database file (default: data/audit_log.db)
    
    Returns:
        The global AuditLog instance
    """
    global _global_audit_log
    
    if _global_audit_log is None:
        _global_audit_log = AuditLog(db_path)
    
    return _global_audit_log
